/*
 * Copyright (c) 2021 HCL CORPORATION.
 * All rights reserved. HCL source code is an unpublished work and the use of a copyright notice does not imply otherwise.
 * This source code contains confidential, trade secret material of HCL. Any attempt or participation in deciphering,
 * decoding, reverse engineering or in any way altering the source code is strictly prohibited, unless the prior written consent of
 * HCL is obtained. This is proprietary and confidential to HCL.
 */

/**
 * @page UserManagement User Management.

* <p><strong>User Management&nbsp;</strong>is used to manage user accounts such as create, view, update, validate, delete, lock/unlock, enable/disable accounts.</p>
* <p><strong>Register User API :</strong></p>
* <p>User registration APIs allow users to self-register a user account. When registering, the user must provide <strong>mandatory</strong> input parameters such as email, phone number and other parameters that will be used to verify the user account For more information on the input parameters see <a class="el" href="class_h_c_l_1_1_c_s_1_1_domain_1_1_models_1_1_user_model.html">UserModel</a> . Self-registered user accounts are <strong>inactive</strong> by default; after user authenticity is validated via email token or phone number OTP, or Authenticator app approval, the user account becomes active. When registering a user account, the HCL.CS.SF will enforce system-level business rules on the user-provided inputs and throw an exception if such rules are not met.&nbsp;</p>
* <p>Some of the bussiness rules are as below:</p>
* <ul>
* <li>Input data length</li>
* <li>Password complexity</li>
* <li>Minimum number of security</li>
* <li>Email</li>
* <li>Phone number</li>
* <li>2FA option etc</li>
* </ul>
* <p>HCL.CS.SF stores the user password in hashed format, it uses ARGON2 algorithm with dynamic salt value.</p>
* <p>User account verification token will be generated based on the two factor mode notification selected during registeration , based on the business need user account verification options shall be enabled in the system, either email or phone or both.</p>
* <ul>
* <li><strong>Email token verification :</strong>User specific token will be generated and same will be sent to email that is provided as part of user account registration via SMTP server. Email token validity will be based on the system configuration set in the client application, user account should be verified within allowed span of time. Otherwise, it will be considered as expired and then user has to generate new token for account verification.&nbsp;</li>
* </ul>
* <ul>
* <li><strong>SMS OTP Verification </strong><strong>:</strong> 6 digits random number will be generated by HCL.CS.SF and sent to user registered phone number, by default OTP will be valid for 10 mins. User has to confirm/verify the SMS OTP token via Phone number verification API within defined span of time, otherwise will be expired. User can also request to regenerate new SMS OTP when expired or if SMS is not received within specified duration.</li>
* </ul>
* <p>User Management also involves Locking and Unlocking user in the system based on circumstances.</p>
* <p><strong>Locking User :</strong></p>
* <p>The user lockout feature is the way to improve application security by locking out a user that enters a password incorrectly several times. This technique can help us in protecting against brute force attacks, where an attacker repeatedly tries to guess a password. There are two ways for Locking User in HCL.CS.SF.</p>
* <ul>
* <li><strong>Permanent Lock :&nbsp;</strong>User is permanently locked. Locked user cannot login into the system, until the user is unlocked by the admin.</li>
* <li><strong>Temporary Lock :</strong>&nbsp;User is temporarily Disabled/locked for particular time duration by admin. Locked user cannot login into the system, until the user is unlocked by the admin or until the lock duration is complete.</li>
* </ul>
* <p><strong>Unlocking User :</strong></p>
* <p>User account will be unlocked by end user by providing HCL.CS.SF generated token and security questioonaire. If the token is expired or incorrect token framework will throw an appropriate error message.</p>
* <p>Password Related Operations are also managed in User Management</p>
* <p><strong>Change password:</strong></p>
* <p>User can change his/her old password by providing the current password and the new password. Current password is usually changed when it is about to expire. The provided new password should meet the password complexity rules provided in the HCL.CS.SF system configuration.</p>
 */


