/*
 * Copyright (c) 2021 HCL CORPORATION.
 * All rights reserved. HCL source code is an unpublished work and the use of a copyright notice does not imply otherwise.
 * This source code contains confidential, trade secret material of HCL. Any attempt or participation in deciphering,
 * decoding, reverse engineering or in any way altering the source code is strictly prohibited, unless the prior written consent of
 * HCL is obtained. This is proprietary and confidential to HCL.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCL.CS.SF.Infrastructure.Resources
{
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.

    /// <summary>
    /// A strongly-typed resource class for looking up localised validation messages.
    /// This class was auto-generated by the StronglyTypedResourceBuilder tool.
    /// Validation message codes follow the convention: AUD = Audit, AUT = Authentication,
    /// COM = Common, CRY = Cryptography, E = Endpoint, USR = User Management.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {

        /// <summary>
        /// Cached <see cref="global::System.Resources.ResourceManager"/> instance used by this class.
        /// </summary>
        private static global::System.Resources.ResourceManager resourceMan;

        /// <summary>
        /// Cached <see cref="global::System.Globalization.CultureInfo"/> instance used for resource lookups.
        /// </summary>
        private static global::System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Initialises a new instance of the <see cref="ValidationMessages"/> class.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }

        /// <summary>
        /// Gets the <see cref="global::System.Resources.ResourceManager"/> instance used to look up resource strings.
        /// Lazily initialised on first access.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HCL.CS.SF.Infrastructure.Resources", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="global::System.Globalization.CultureInfo"/> used for resource lookups.
        /// When <c>null</c>, the current thread's culture is used.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Gets the localised validation message string for audit code AUD1001.
        /// </summary>
        public static string AUD1001 {
            get {
                return ResourceManager.GetString("AUD1001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for audit code AUD1002.
        /// </summary>
        public static string AUD1002 {
            get {
                return ResourceManager.GetString("AUD1002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for audit code AUD1003.
        /// </summary>
        public static string AUD1003 {
            get {
                return ResourceManager.GetString("AUD1003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2001.
        /// </summary>
        public static string AUT2001 {
            get {
                return ResourceManager.GetString("AUT2001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2002.
        /// </summary>
        public static string AUT2002 {
            get {
                return ResourceManager.GetString("AUT2002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2003.
        /// </summary>
        public static string AUT2003 {
            get {
                return ResourceManager.GetString("AUT2003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2004.
        /// </summary>
        public static string AUT2004 {
            get {
                return ResourceManager.GetString("AUT2004", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2005.
        /// </summary>
        public static string AUT2005 {
            get {
                return ResourceManager.GetString("AUT2005", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2006.
        /// </summary>
        public static string AUT2006 {
            get {
                return ResourceManager.GetString("AUT2006", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2007.
        /// </summary>
        public static string AUT2007 {
            get {
                return ResourceManager.GetString("AUT2007", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2008.
        /// </summary>
        public static string AUT2008 {
            get {
                return ResourceManager.GetString("AUT2008", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2009.
        /// </summary>
        public static string AUT2009 {
            get {
                return ResourceManager.GetString("AUT2009", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2010.
        /// </summary>
        public static string AUT2010 {
            get {
                return ResourceManager.GetString("AUT2010", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2011.
        /// </summary>
        public static string AUT2011 {
            get {
                return ResourceManager.GetString("AUT2011", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for authentication code AUT2012.
        /// </summary>
        public static string AUT2012 {
            get {
                return ResourceManager.GetString("AUT2012", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5001.
        /// </summary>
        public static string COM5001 {
            get {
                return ResourceManager.GetString("COM5001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5002.
        /// </summary>
        public static string COM5002 {
            get {
                return ResourceManager.GetString("COM5002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5003.
        /// </summary>
        public static string COM5003 {
            get {
                return ResourceManager.GetString("COM5003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5004.
        /// </summary>
        public static string COM5004 {
            get {
                return ResourceManager.GetString("COM5004", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5005.
        /// </summary>
        public static string COM5005 {
            get {
                return ResourceManager.GetString("COM5005", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for common code COM5006.
        /// </summary>
        public static string COM5006 {
            get {
                return ResourceManager.GetString("COM5006", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3001.
        /// </summary>
        public static string CRY3001 {
            get {
                return ResourceManager.GetString("CRY3001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3002.
        /// </summary>
        public static string CRY3002 {
            get {
                return ResourceManager.GetString("CRY3002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3003.
        /// </summary>
        public static string CRY3003 {
            get {
                return ResourceManager.GetString("CRY3003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3004.
        /// </summary>
        public static string CRY3004 {
            get {
                return ResourceManager.GetString("CRY3004", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3005.
        /// </summary>
        public static string CRY3005 {
            get {
                return ResourceManager.GetString("CRY3005", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3006.
        /// </summary>
        public static string CRY3006 {
            get {
                return ResourceManager.GetString("CRY3006", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for cryptography code CRY3007.
        /// </summary>
        public static string CRY3007 {
            get {
                return ResourceManager.GetString("CRY3007", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1001.
        /// </summary>
        public static string E1001 {
            get {
                return ResourceManager.GetString("E1001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1002.
        /// </summary>
        public static string E1002 {
            get {
                return ResourceManager.GetString("E1002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1003.
        /// </summary>
        public static string E1003 {
            get {
                return ResourceManager.GetString("E1003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1006.
        /// </summary>
        public static string E1006 {
            get {
                return ResourceManager.GetString("E1006", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1008.
        /// </summary>
        public static string E1008 {
            get {
                return ResourceManager.GetString("E1008", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for endpoint code E1010.
        /// </summary>
        public static string E1010 {
            get {
                return ResourceManager.GetString("E1010", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4001.
        /// </summary>
        public static string USR4001 {
            get {
                return ResourceManager.GetString("USR4001", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4002.
        /// </summary>
        public static string USR4002 {
            get {
                return ResourceManager.GetString("USR4002", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4003.
        /// </summary>
        public static string USR4003 {
            get {
                return ResourceManager.GetString("USR4003", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4004.
        /// </summary>
        public static string USR4004 {
            get {
                return ResourceManager.GetString("USR4004", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4005.
        /// </summary>
        public static string USR4005 {
            get {
                return ResourceManager.GetString("USR4005", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4006.
        /// </summary>
        public static string USR4006 {
            get {
                return ResourceManager.GetString("USR4006", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4007.
        /// </summary>
        public static string USR4007 {
            get {
                return ResourceManager.GetString("USR4007", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4008.
        /// </summary>
        public static string USR4008 {
            get {
                return ResourceManager.GetString("USR4008", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4009.
        /// </summary>
        public static string USR4009 {
            get {
                return ResourceManager.GetString("USR4009", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4010.
        /// </summary>
        public static string USR4010 {
            get {
                return ResourceManager.GetString("USR4010", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4011.
        /// </summary>
        public static string USR4011 {
            get {
                return ResourceManager.GetString("USR4011", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4012.
        /// </summary>
        public static string USR4012 {
            get {
                return ResourceManager.GetString("USR4012", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the localised validation message string for user management code USR4013.
        /// </summary>
        public static string USR4013 {
            get {
                return ResourceManager.GetString("USR4013", resourceCulture);
            }
        }
    }
}



